// Generated by mgfront.py -- do not edit. C++ view of compiled Mountain Goat functions.
#pragma once
#include <cstdint>
#include <cstdlib>
#include <stdexcept>
#include <string>
#include <vector>

namespace mg {
// A dense row-major f64 matrix that owns its storage.
struct Matrix {
  int64_t rows = 0, cols = 0;
  std::vector<double> data;
  Matrix() = default;
  Matrix(int64_t r, int64_t c, std::vector<double> d) : rows(r), cols(c), data(std::move(d)) {
    if ((int64_t)data.size() != r * c) throw std::invalid_argument("Matrix: data size != rows*cols");
  }
  double &operator()(int64_t i, int64_t j) { return data[i * cols + j]; }
  double operator()(int64_t i, int64_t j) const { return data[i * cols + j]; }
};
// The memref descriptor the compiled code returns (rank 2).
struct Desc { double *allocated, *aligned; int64_t offset, sizes[2], strides[2]; };
inline Matrix take(Desc d) {   // copy out through the strides, then release the callee's malloc
  Matrix m; m.rows = d.sizes[0]; m.cols = d.sizes[1]; m.data.resize(m.rows * m.cols);
  for (int64_t i = 0; i < m.rows; i++)
    for (int64_t j = 0; j < m.cols; j++)
      m.data[i * m.cols + j] = d.aligned[d.offset + i * d.strides[0] + j * d.strides[1]];
  std::free(d.allocated);
  return m;
}
inline void expect(const Matrix &m, int64_t r, int64_t c, const char *fn, const char *arg) {
  if ((r >= 0 && m.rows != r) || (c >= 0 && m.cols != c))
    throw std::invalid_argument(std::string(fn) + ": argument '" + arg + "' has the wrong shape");
}
}  // namespace mg

extern "C" {
mg::Desc add(double*, double*, int64_t, int64_t, int64_t, int64_t, int64_t, double*, double*, int64_t, int64_t, int64_t, int64_t, int64_t);
mg::Desc add_t(double*, double*, int64_t, int64_t, int64_t, int64_t, int64_t, double*, double*, int64_t, int64_t, int64_t, int64_t, int64_t);
mg::Desc scale2(double*, double*, int64_t, int64_t, int64_t, int64_t, int64_t);
mg::Desc rot(double*, double*, int64_t, int64_t, int64_t, int64_t, int64_t);
}

namespace mg {
// add(a: ?x?, b: ?x?)
inline Matrix add(const Matrix &a, const Matrix &b) {
  return take(::add(const_cast<double*>(a.data.data()), const_cast<double*>(a.data.data()), 0, a.rows, a.cols, a.cols, 1, const_cast<double*>(b.data.data()), const_cast<double*>(b.data.data()), 0, b.rows, b.cols, b.cols, 1));
}
// add_t(a: ?x?, b: ?x?)
inline Matrix add_t(const Matrix &a, const Matrix &b) {
  return take(::add_t(const_cast<double*>(a.data.data()), const_cast<double*>(a.data.data()), 0, a.rows, a.cols, a.cols, 1, const_cast<double*>(b.data.data()), const_cast<double*>(b.data.data()), 0, b.rows, b.cols, b.cols, 1));
}
// scale2(a: ?x?)
inline Matrix scale2(const Matrix &a) {
  return take(::scale2(const_cast<double*>(a.data.data()), const_cast<double*>(a.data.data()), 0, a.rows, a.cols, a.cols, 1));
}
// rot(a: 2x3)
inline Matrix rot(const Matrix &a) {
  expect(a, 2, 3, "rot", "a");
  return take(::rot(const_cast<double*>(a.data.data()), const_cast<double*>(a.data.data()), 0, a.rows, a.cols, a.cols, 1));
}
}  // namespace mg
