# generated by autograd.py from tmp_509nfc4.mg: prints, in order: sum(g*v), H*v
# ---- forward pass: the program's own operations, one `let` each
let x = [[0.7, -1.3, 2.1], [1.4, 0.2, -0.6]]
let v1 = (x * x)
let v2 = exp(x)
let v3 = [[1.0]]
let v4 = [[1.0], [1.0]]
let ones6 = [[1.0], [1.0]]
let v5 = (v3 * ones6)
let v7 = (v4 * v5)
let v8 = [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
let ones10 = [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
let v9 = (v7 * ones10)
let v11 = (v8 * v9)
let v12 = (v11 * 0.5)
let v13 = (v12 * v2)
let v14 = (v11 * x)
let v15 = (v11 * v1)
let v16 = (v13 + v15)
let v17 = (v14 * x)
let v18 = (v16 + v17)
let v19 = (v14 * x)
let v20 = (v18 + v19)
let v21 = [[1.0, 0.0, 0.0], [0.0, 0.0, 0.0]]
let v22 = (v20 * v21)
let v23 = row_sum(v22)
let v24 = col_sum(v23)
# ---- backward pass: the operations in reverse; each adjoint g is d(loss)/d(the value it belongs to)
let g25 = [[1.0]]
let g26 = (ones6 * g25)
let g27 = (ones10 * g26)
let g28 = (g27 * v21)
let g29 = (g27 * v20)
let g30 = g28
let g31 = g28
let g32 = (g31 * x)
let g33 = (g31 * v14)
let g34 = g30
let g35 = g30
let g36 = (g32 + (g35 * x))
let g37 = (g33 + (g35 * v14))
let g38 = g34
let g39 = g34
let g40 = (g39 * v1)
let g41 = (g39 * v11)
let g42 = (g40 + (g36 * x))
let g43 = (g37 + (g36 * v11))
let g44 = (g38 * v2)
let g45 = (g38 * v12)
let g46 = (g42 + (g44 * 0.5))
let g47 = (g46 * v9)
let g48 = (g46 * v8)
let g49 = row_sum(g48)
let g50 = (g49 * v5)
let g51 = (g49 * v4)
let g52 = col_sum(g51)
let g53 = (g43 + (g45 * v2))
let g54 = (g53 + (g41 * x))
let g55 = (g54 + (g41 * x))
# ---- results: the loss, then the gradient of each requested matrix
print v24
print g55
