// Generated by mgfront.py -- do not edit. C++ view of compiled Mountain Goat functions.
#pragma once
#include <cstdint>
#include <cstdlib>
#include <stdexcept>
#include <string>
#include <vector>

namespace mg {
// A dense row-major f64 matrix that owns its storage.
struct Matrix {
  int64_t rows = 0, cols = 0;
  std::vector<double> data;
  Matrix() = default;
  Matrix(int64_t r, int64_t c, std::vector<double> d) : rows(r), cols(c), data(std::move(d)) {
    if ((int64_t)data.size() != r * c) throw std::invalid_argument("Matrix: data size != rows*cols");
  }
  double &operator()(int64_t i, int64_t j) { return data[i * cols + j]; }
  double operator()(int64_t i, int64_t j) const { return data[i * cols + j]; }
};
// The memref descriptor the compiled code returns (rank 2).
struct Desc { double *allocated, *aligned; int64_t offset, sizes[2], strides[2]; };
inline Matrix take(Desc d) {   // copy out through the strides, then release the callee's malloc
  Matrix m; m.rows = d.sizes[0]; m.cols = d.sizes[1]; m.data.resize(m.rows * m.cols);
  for (int64_t i = 0; i < m.rows; i++)
    for (int64_t j = 0; j < m.cols; j++)
      m.data[i * m.cols + j] = d.aligned[d.offset + i * d.strides[0] + j * d.strides[1]];
  std::free(d.allocated);
  return m;
}
inline void expect(const Matrix &m, int64_t r, int64_t c, const char *fn, const char *arg) {
  if ((r >= 0 && m.rows != r) || (c >= 0 && m.cols != c))
    throw std::invalid_argument(std::string(fn) + ": argument '" + arg + "' has the wrong shape");
}
}  // namespace mg

extern "C" {
mg::Desc relu_m(double*, double*, int64_t, int64_t, int64_t, int64_t, int64_t);
mg::Desc row_sums(double*, double*, int64_t, int64_t, int64_t, int64_t, int64_t);
mg::Desc col_maxes(double*, double*, int64_t, int64_t, int64_t, int64_t, int64_t);
mg::Desc layer(double*, double*, int64_t, int64_t, int64_t, int64_t, int64_t, double*, double*, int64_t, int64_t, int64_t, int64_t, int64_t, double*, double*, int64_t, int64_t, int64_t, int64_t, int64_t);
mg::Desc center(double*, double*, int64_t, int64_t, int64_t, int64_t, int64_t);
}

namespace mg {
// relu_m(a: ?x?)
inline Matrix relu_m(const Matrix &a) {
  return take(::relu_m(const_cast<double*>(a.data.data()), const_cast<double*>(a.data.data()), 0, a.rows, a.cols, a.cols, 1));
}
// row_sums(a: ?x?)
inline Matrix row_sums(const Matrix &a) {
  return take(::row_sums(const_cast<double*>(a.data.data()), const_cast<double*>(a.data.data()), 0, a.rows, a.cols, a.cols, 1));
}
// col_maxes(a: ?x?)
inline Matrix col_maxes(const Matrix &a) {
  return take(::col_maxes(const_cast<double*>(a.data.data()), const_cast<double*>(a.data.data()), 0, a.rows, a.cols, a.cols, 1));
}
// layer(x: 4x6, w: 6x3, bias: 1x3)
inline Matrix layer(const Matrix &x, const Matrix &w, const Matrix &bias) {
  expect(x, 4, 6, "layer", "x");
  expect(w, 6, 3, "layer", "w");
  expect(bias, 1, 3, "layer", "bias");
  return take(::layer(const_cast<double*>(x.data.data()), const_cast<double*>(x.data.data()), 0, x.rows, x.cols, x.cols, 1, const_cast<double*>(w.data.data()), const_cast<double*>(w.data.data()), 0, w.rows, w.cols, w.cols, 1, const_cast<double*>(bias.data.data()), const_cast<double*>(bias.data.data()), 0, bias.rows, bias.cols, bias.cols, 1));
}
// center(a: 5x4)
inline Matrix center(const Matrix &a) {
  expect(a, 5, 4, "center", "a");
  return take(::center(const_cast<double*>(a.data.data()), const_cast<double*>(a.data.data()), 0, a.rows, a.cols, a.cols, 1));
}
}  // namespace mg
