# generated by autograd.py from 00_worked_example.mg: prints, in order: loss, grad w, grad x
# ---- forward pass: the program's own operations, one `let` each
let x = [[0.5, -1.0], [2.0, 1.0]]
let w = [[1.0, 2.0], [3.0, 4.0]]
let v1 = (x @ w)
let v2 = relu(v1)
let v3 = (v2 * 2.0)
let v4 = row_sum(v3)
let v5 = col_sum(v4)
# ---- backward pass: the operations in reverse; each adjoint g is d(loss)/d(the value it belongs to)
let g6 = [[1.0]]
let ones7 = [[1.0], [1.0]]
let g8 = (ones7 * g6)
let ones9 = [[1.0, 1.0], [1.0, 1.0]]
let g10 = (ones9 * g8)
let g11 = (g10 * 2.0)
let zero12 = [[0.0]]
let g13 = (g11 * ge(v1, zero12))
let g14 = (g13 @ transpose(w))
let g15 = (transpose(x) @ g13)
# ---- results: the loss, then the gradient of each requested matrix
print v5
print g15
print g14
