module attributes {gpu.container_module} {
  llvm.func @malloc(i64) -> !llvm.ptr
  llvm.func @add_tensors(%arg0: !llvm.ptr, %arg1: !llvm.ptr, %arg2: i64, %arg3: i64, %arg4: i64, %arg5: i64, %arg6: i64, %arg7: !llvm.ptr, %arg8: !llvm.ptr, %arg9: i64, %arg10: i64, %arg11: i64, %arg12: i64, %arg13: i64) -> !llvm.struct<(ptr, ptr, i64, array<2 x i64>, array<2 x i64>)> {
    %0 = llvm.mlir.constant(0 : i8) : i8
    %1 = llvm.mlir.constant(0 : index) : i64
    %2 = llvm.mlir.constant(1 : index) : i64
    %3 = llvm.mlir.constant(2 : index) : i64
    %4 = llvm.call @mgpuStreamCreate() : () -> !llvm.ptr
    %5 = llvm.mlir.zero : !llvm.ptr
    %6 = llvm.getelementptr %5[4] : (!llvm.ptr) -> !llvm.ptr, f64
    %7 = llvm.ptrtoint %6 : !llvm.ptr to i64
    %8 = llvm.call @mgpuMemAlloc(%7, %4, %0) : (i64, !llvm.ptr, i8) -> !llvm.ptr
    %9 = llvm.call @mgpuMemAlloc(%7, %4, %0) : (i64, !llvm.ptr, i8) -> !llvm.ptr
    %10 = llvm.call @mgpuMemAlloc(%7, %4, %0) : (i64, !llvm.ptr, i8) -> !llvm.ptr
    llvm.call @mgpuMemcpy(%8, %arg1, %7, %4) : (!llvm.ptr, !llvm.ptr, i64, !llvm.ptr) -> ()
    llvm.call @mgpuMemcpy(%9, %arg8, %7, %4) : (!llvm.ptr, !llvm.ptr, i64, !llvm.ptr) -> ()
    gpu.launch_func <%4 : !llvm.ptr> @add_tensors_kernel::@add_tensors_kernel blocks in (%3, %2, %2) threads in (%3, %2, %2) : i64 args(%2 : i64, %1 : i64, %8 : !llvm.ptr, %8 : !llvm.ptr, %1 : i64, %3 : i64, %3 : i64, %3 : i64, %2 : i64, %9 : !llvm.ptr, %9 : !llvm.ptr, %1 : i64, %3 : i64, %3 : i64, %3 : i64, %2 : i64, %10 : !llvm.ptr, %10 : !llvm.ptr, %1 : i64, %3 : i64, %3 : i64, %3 : i64, %2 : i64)
    llvm.call @mgpuStreamSynchronize(%4) : (!llvm.ptr) -> ()
    llvm.call @mgpuStreamDestroy(%4) : (!llvm.ptr) -> ()
    %11 = llvm.call @malloc(%7) : (i64) -> !llvm.ptr
    %12 = llvm.mlir.undef : !llvm.struct<(ptr, ptr, i64, array<2 x i64>, array<2 x i64>)>
    %13 = llvm.insertvalue %11, %12[0] : !llvm.struct<(ptr, ptr, i64, array<2 x i64>, array<2 x i64>)> 
    %14 = llvm.insertvalue %11, %13[1] : !llvm.struct<(ptr, ptr, i64, array<2 x i64>, array<2 x i64>)> 
    %15 = llvm.insertvalue %1, %14[2] : !llvm.struct<(ptr, ptr, i64, array<2 x i64>, array<2 x i64>)> 
    %16 = llvm.insertvalue %3, %15[3, 0] : !llvm.struct<(ptr, ptr, i64, array<2 x i64>, array<2 x i64>)> 
    %17 = llvm.insertvalue %3, %16[3, 1] : !llvm.struct<(ptr, ptr, i64, array<2 x i64>, array<2 x i64>)> 
    %18 = llvm.insertvalue %3, %17[4, 0] : !llvm.struct<(ptr, ptr, i64, array<2 x i64>, array<2 x i64>)> 
    %19 = llvm.insertvalue %2, %18[4, 1] : !llvm.struct<(ptr, ptr, i64, array<2 x i64>, array<2 x i64>)> 
    %20 = llvm.call @mgpuStreamCreate() : () -> !llvm.ptr
    llvm.call @mgpuMemcpy(%11, %10, %7, %20) : (!llvm.ptr, !llvm.ptr, i64, !llvm.ptr) -> ()
    llvm.call @mgpuMemFree(%8, %20) : (!llvm.ptr, !llvm.ptr) -> ()
    llvm.call @mgpuMemFree(%9, %20) : (!llvm.ptr, !llvm.ptr) -> ()
    llvm.call @mgpuMemFree(%10, %20) : (!llvm.ptr, !llvm.ptr) -> ()
    llvm.call @mgpuStreamSynchronize(%20) : (!llvm.ptr) -> ()
    llvm.call @mgpuStreamDestroy(%20) : (!llvm.ptr) -> ()
    llvm.return %19 : !llvm.struct<(ptr, ptr, i64, array<2 x i64>, array<2 x i64>)>
  }
  gpu.binary @add_tensors_kernel  [#gpu.object<#nvvm.target<chip = "sm_70">, properties = {O = 2 : i32}, assembly = "//\0A// Generated by LLVM NVPTX Back-End\0A//\0A\0A.version 6.0\0A.target sm_70\0A.address_size 64\0A\0A\09// .globl\09add_tensors_kernel\0A\0A.visible .entry add_tensors_kernel(\0A\09.param .u64 add_tensors_kernel_param_0,\0A\09.param .u64 add_tensors_kernel_param_1,\0A\09.param .u64 add_tensors_kernel_param_2,\0A\09.param .u64 add_tensors_kernel_param_3,\0A\09.param .u64 add_tensors_kernel_param_4,\0A\09.param .u64 add_tensors_kernel_param_5,\0A\09.param .u64 add_tensors_kernel_param_6,\0A\09.param .u64 add_tensors_kernel_param_7,\0A\09.param .u64 add_tensors_kernel_param_8,\0A\09.param .u64 add_tensors_kernel_param_9,\0A\09.param .u64 add_tensors_kernel_param_10,\0A\09.param .u64 add_tensors_kernel_param_11,\0A\09.param .u64 add_tensors_kernel_param_12,\0A\09.param .u64 add_tensors_kernel_param_13,\0A\09.param .u64 add_tensors_kernel_param_14,\0A\09.param .u64 add_tensors_kernel_param_15,\0A\09.param .u64 add_tensors_kernel_param_16,\0A\09.param .u64 add_tensors_kernel_param_17,\0A\09.param .u64 add_tensors_kernel_param_18,\0A\09.param .u64 add_tensors_kernel_param_19,\0A\09.param .u64 add_tensors_kernel_param_20,\0A\09.param .u64 add_tensors_kernel_param_21,\0A\09.param .u64 add_tensors_kernel_param_22\0A)\0A{\0A\09.reg .b32 \09%r<3>;\0A\09.reg .b64 \09%rd<19>;\0A\09.reg .f64 \09%fd<4>;\0A\0A\09ld.param.u64 \09%rd1, [add_tensors_kernel_param_0];\0A\09ld.param.u64 \09%rd2, [add_tensors_kernel_param_17];\0A\09cvta.to.global.u64 \09%rd3, %rd2;\0A\09ld.param.u64 \09%rd4, [add_tensors_kernel_param_1];\0A\09ld.param.u64 \09%rd5, [add_tensors_kernel_param_10];\0A\09cvta.to.global.u64 \09%rd6, %rd5;\0A\09ld.param.u64 \09%rd7, [add_tensors_kernel_param_3];\0A\09cvta.to.global.u64 \09%rd8, %rd7;\0A\09mov.u32 \09%r1, %ctaid.x;\0A\09cvt.s64.s32 \09%rd9, %r1;\0A\09mov.u32 \09%r2, %tid.x;\0A\09cvt.s64.s32 \09%rd10, %r2;\0A\09mul.lo.s64 \09%rd11, %rd9, %rd1;\0A\09add.s64 \09%rd12, %rd11, %rd4;\0A\09shl.b64 \09%rd13, %rd12, 1;\0A\09add.s64 \09%rd14, %rd13, %rd10;\0A\09shl.b64 \09%rd15, %rd14, 3;\0A\09add.s64 \09%rd16, %rd8, %rd15;\0A\09ld.global.f64 \09%fd1, [%rd16];\0A\09add.s64 \09%rd17, %rd6, %rd15;\0A\09ld.global.f64 \09%fd2, [%rd17];\0A\09add.rn.f64 \09%fd3, %fd1, %fd2;\0A\09add.s64 \09%rd18, %rd3, %rd15;\0A\09st.global.f64 \09[%rd18], %fd3;\0A\09ret;\0A\0A}\0A\00">]
  llvm.func @mgpuStreamCreate() -> !llvm.ptr
  llvm.func @mgpuMemAlloc(i64, !llvm.ptr, i8) -> !llvm.ptr
  llvm.func @mgpuMemcpy(!llvm.ptr, !llvm.ptr, i64, !llvm.ptr)
  llvm.func @mgpuStreamSynchronize(!llvm.ptr)
  llvm.func @mgpuStreamDestroy(!llvm.ptr)
  llvm.func @mgpuMemFree(!llvm.ptr, !llvm.ptr)
}

