// Generated by mgfront.py -- do not edit. C++ view of compiled Mountain Goat functions.
#pragma once
#include <cstdint>
#include <cstdlib>
#include <stdexcept>
#include <string>
#include <vector>

namespace mg {
// A dense row-major f64 matrix that owns its storage.
struct Matrix {
  int64_t rows = 0, cols = 0;
  std::vector<double> data;
  Matrix() = default;
  Matrix(int64_t r, int64_t c, std::vector<double> d) : rows(r), cols(c), data(std::move(d)) {
    if ((int64_t)data.size() != r * c) throw std::invalid_argument("Matrix: data size != rows*cols");
  }
  double &operator()(int64_t i, int64_t j) { return data[i * cols + j]; }
  double operator()(int64_t i, int64_t j) const { return data[i * cols + j]; }
};
// The memref descriptor the compiled code returns (rank 2).
struct Desc { double *allocated, *aligned; int64_t offset, sizes[2], strides[2]; };
inline Matrix take(Desc d) {   // copy out through the strides, then release the callee's malloc
  Matrix m; m.rows = d.sizes[0]; m.cols = d.sizes[1]; m.data.resize(m.rows * m.cols);
  for (int64_t i = 0; i < m.rows; i++)
    for (int64_t j = 0; j < m.cols; j++)
      m.data[i * m.cols + j] = d.aligned[d.offset + i * d.strides[0] + j * d.strides[1]];
  std::free(d.allocated);
  return m;
}
inline void expect(const Matrix &m, int64_t r, int64_t c, const char *fn, const char *arg) {
  if ((r >= 0 && m.rows != r) || (c >= 0 && m.cols != c))
    throw std::invalid_argument(std::string(fn) + ": argument '" + arg + "' has the wrong shape");
}
}  // namespace mg

extern "C" {
mg::Desc grad(double*, double*, int64_t, int64_t, int64_t, int64_t, int64_t, double*, double*, int64_t, int64_t, int64_t, int64_t, int64_t, double*, double*, int64_t, int64_t, int64_t, int64_t, int64_t);
mg::Desc step(double*, double*, int64_t, int64_t, int64_t, int64_t, int64_t, double*, double*, int64_t, int64_t, int64_t, int64_t, int64_t, double*, double*, int64_t, int64_t, int64_t, int64_t, int64_t, double*, double*, int64_t, int64_t, int64_t, int64_t, int64_t);
mg::Desc loss_sum(double*, double*, int64_t, int64_t, int64_t, int64_t, int64_t, double*, double*, int64_t, int64_t, int64_t, int64_t, int64_t, double*, double*, int64_t, int64_t, int64_t, int64_t, int64_t);
}

namespace mg {
// grad(x: ?x4, y: ?x1, p: 4x1)
inline Matrix grad(const Matrix &x, const Matrix &y, const Matrix &p) {
  expect(x, -1, 4, "grad", "x");
  expect(y, -1, 1, "grad", "y");
  expect(p, 4, 1, "grad", "p");
  return take(::grad(const_cast<double*>(x.data.data()), const_cast<double*>(x.data.data()), 0, x.rows, x.cols, x.cols, 1, const_cast<double*>(y.data.data()), const_cast<double*>(y.data.data()), 0, y.rows, y.cols, y.cols, 1, const_cast<double*>(p.data.data()), const_cast<double*>(p.data.data()), 0, p.rows, p.cols, p.cols, 1));
}
// step(x: ?x4, y: ?x1, p: 4x1, rate: 1x1)
inline Matrix step(const Matrix &x, const Matrix &y, const Matrix &p, const Matrix &rate) {
  expect(x, -1, 4, "step", "x");
  expect(y, -1, 1, "step", "y");
  expect(p, 4, 1, "step", "p");
  expect(rate, 1, 1, "step", "rate");
  return take(::step(const_cast<double*>(x.data.data()), const_cast<double*>(x.data.data()), 0, x.rows, x.cols, x.cols, 1, const_cast<double*>(y.data.data()), const_cast<double*>(y.data.data()), 0, y.rows, y.cols, y.cols, 1, const_cast<double*>(p.data.data()), const_cast<double*>(p.data.data()), 0, p.rows, p.cols, p.cols, 1, const_cast<double*>(rate.data.data()), const_cast<double*>(rate.data.data()), 0, rate.rows, rate.cols, rate.cols, 1));
}
// loss_sum(x: ?x4, y: ?x1, p: 4x1)
inline Matrix loss_sum(const Matrix &x, const Matrix &y, const Matrix &p) {
  expect(x, -1, 4, "loss_sum", "x");
  expect(y, -1, 1, "loss_sum", "y");
  expect(p, 4, 1, "loss_sum", "p");
  return take(::loss_sum(const_cast<double*>(x.data.data()), const_cast<double*>(x.data.data()), 0, x.rows, x.cols, x.cols, 1, const_cast<double*>(y.data.data()), const_cast<double*>(y.data.data()), 0, y.rows, y.cols, y.cols, 1, const_cast<double*>(p.data.data()), const_cast<double*>(p.data.data()), 0, p.rows, p.cols, p.cols, 1));
}
}  // namespace mg
