// Tensor contractions from first principles, with Mountain Goat doing the arithmetic.
//
//   contract_reference : the DEFINITION, written directly: for every output index, add up the products over every contracted index.
//                        No matrix product anywhere. It exists to check the other one.
//   contract_ttgt      : "transpose, reshape, GEMM, reshape": permute each tensor so its free axes come first (A) or last (B) and its
//                        contracted axes come last (A) or first (B), flatten each to a matrix, multiply the two matrices with the
//                        compiled Mountain Goat gemm (an @), and reshape the product to the output shape.
//
// Mountain Goat only has two-dimensional matrices, so the bookkeeping over N axes (permuting, flattening) is C++ here, and the whole sum
// of products is the language's matrix product.
#pragma once
#include <algorithm>
#include <cstdint>
#include <functional>
#include <stdexcept>
#include <string>
#include <vector>
#include "contract.h"   // generated by `mgc lib contract.mg`: mg::Matrix and mg::gemm

struct Tensor {
  std::vector<int> shape;       // row-major: the last axis varies fastest. An empty shape is a scalar (one element).
  std::vector<double> data;
  explicit Tensor(std::vector<int> s) : shape(std::move(s)) {
    long long total = 1; for (int d : shape) total *= d;
    data.assign((size_t)total, 0.0);
  }
};

inline long long product(const std::vector<int> &dims) { long long p = 1; for (int d : dims) p *= d; return p; }   // empty product is 1

inline std::vector<long long> row_major_strides(const std::vector<int> &shape) {
  std::vector<long long> strides(shape.size()); long long acc = 1;
  for (int i = (int)shape.size() - 1; i >= 0; i--) { strides[i] = acc; acc *= shape[i]; }
  return strides;
}

// Visit every multi-index of `shape` in row-major order (once, with an empty index, if the shape is empty).
inline void for_each_index(const std::vector<int> &shape, const std::function<void(const std::vector<int> &)> &visit) {
  std::vector<int> idx(shape.size(), 0);
  while (true) {
    visit(idx);
    int axis = (int)shape.size() - 1;
    while (axis >= 0 && ++idx[axis] == shape[axis]) { idx[axis] = 0; axis--; }
    if (axis < 0) return;
  }
}

// Check the axis lists. Throws std::invalid_argument; the first problem found is reported.
inline void validate(const Tensor &A, const std::vector<int> &axes_a, const Tensor &B, const std::vector<int> &axes_b) {
  if (axes_a.size() != axes_b.size()) throw std::invalid_argument("contract: axes_a and axes_b must have the same length");
  auto check_axes = [](const char *name, const Tensor &T, const std::vector<int> &axes) {
    std::vector<int> seen;
    for (int a : axes) {
      if (a < 0 || a >= (int)T.shape.size()) throw std::invalid_argument(std::string("contract: axis ") + std::to_string(a) + " is out of range for " + name);
      if (std::find(seen.begin(), seen.end(), a) != seen.end()) throw std::invalid_argument(std::string("contract: axis ") + std::to_string(a) + " is listed twice for " + name);
      seen.push_back(a);
    }
  };
  check_axes("A", A, axes_a); check_axes("B", B, axes_b);
  for (size_t k = 0; k < axes_a.size(); k++) {
    int da = A.shape[axes_a[k]], db = B.shape[axes_b[k]];
    if (da != db)
      throw std::invalid_argument("contract: mismatched dimension on contracted axis pair " + std::to_string(k) + " (A.shape[" + std::to_string(axes_a[k]) +
                                  "]=" + std::to_string(da) + " vs B.shape[" + std::to_string(axes_b[k]) + "]=" + std::to_string(db) + ")");
  }
}

inline std::vector<int> free_axes(int rank, const std::vector<int> &contracted) {
  std::vector<int> f; for (int a = 0; a < rank; a++) if (std::find(contracted.begin(), contracted.end(), a) == contracted.end()) f.push_back(a); return f;
}

// ---- 1. The definition, directly ----
inline Tensor contract_reference(const Tensor &A, const std::vector<int> &axes_a, const Tensor &B, const std::vector<int> &axes_b) {
  validate(A, axes_a, B, axes_b);
  std::vector<int> fa = free_axes((int)A.shape.size(), axes_a), fb = free_axes((int)B.shape.size(), axes_b);
  std::vector<int> out_shape, contracted_shape;
  for (int a : fa) out_shape.push_back(A.shape[a]);
  for (int b : fb) out_shape.push_back(B.shape[b]);
  for (int a : axes_a) contracted_shape.push_back(A.shape[a]);
  Tensor C(out_shape);
  auto sA = row_major_strides(A.shape), sB = row_major_strides(B.shape), sC = row_major_strides(out_shape);
  for_each_index(out_shape, [&](const std::vector<int> &out_idx) {
    long long offA = 0, offB = 0, offC = 0;
    for (size_t i = 0; i < fa.size(); i++) offA += out_idx[i] * sA[fa[i]];
    for (size_t j = 0; j < fb.size(); j++) offB += out_idx[fa.size() + j] * sB[fb[j]];
    for (size_t i = 0; i < out_idx.size(); i++) offC += out_idx[i] * sC[i];
    double acc = 0.0;
    for_each_index(contracted_shape, [&](const std::vector<int> &c) {
      long long a = offA, b = offB;
      for (size_t k = 0; k < c.size(); k++) { a += c[k] * sA[axes_a[k]]; b += c[k] * sB[axes_b[k]]; }
      acc += A.data[a] * B.data[b];
    });
    C.data[offC] = acc;
  });
  return C;
}

// ---- 2. Transpose, reshape, GEMM, reshape ----
// Copy T into a new tensor whose axis i is T's axis perm[i].
inline Tensor permute(const Tensor &T, const std::vector<int> &perm) {
  std::vector<int> shape; for (int p : perm) shape.push_back(T.shape[p]);
  Tensor R(shape);
  auto sT = row_major_strides(T.shape); long long pos = 0;
  for_each_index(shape, [&](const std::vector<int> &idx) {
    long long off = 0; for (size_t i = 0; i < idx.size(); i++) off += idx[i] * sT[perm[i]];
    R.data[pos++] = T.data[off];
  });
  return R;
}

// With validate_axes = false the axis check is skipped (to show what Mountain Goat's own run-time check does about a mismatch).
inline Tensor contract_ttgt(const Tensor &A, const std::vector<int> &axes_a, const Tensor &B, const std::vector<int> &axes_b, bool validate_axes = true) {
  if (validate_axes) validate(A, axes_a, B, axes_b);
  std::vector<int> fa = free_axes((int)A.shape.size(), axes_a), fb = free_axes((int)B.shape.size(), axes_b);
  // A: free axes first, contracted axes last.   B: contracted axes first (in the same pairing order), free axes last.
  std::vector<int> perm_a = fa; perm_a.insert(perm_a.end(), axes_a.begin(), axes_a.end());
  std::vector<int> perm_b = axes_b; perm_b.insert(perm_b.end(), fb.begin(), fb.end());
  Tensor Ap = permute(A, perm_a), Bp = permute(B, perm_b);
  std::vector<int> free_a_dims, free_b_dims, contracted_a, contracted_b;
  for (int a : fa) free_a_dims.push_back(A.shape[a]);
  for (int b : fb) free_b_dims.push_back(B.shape[b]);
  for (int a : axes_a) contracted_a.push_back(A.shape[a]);
  for (int b : axes_b) contracted_b.push_back(B.shape[b]);
  // Reshape = reinterpret the (now contiguous) buffer as a matrix: no data moves.
  mg::Matrix Am((int64_t)product(free_a_dims), (int64_t)product(contracted_a), Ap.data);
  mg::Matrix Bm((int64_t)product(contracted_b), (int64_t)product(free_b_dims), Bp.data);
  mg::Matrix Cm = mg::gemm(Am, Bm);                      // <-- the whole sum of products, in compiled Mountain Goat
  std::vector<int> out_shape = free_a_dims; out_shape.insert(out_shape.end(), free_b_dims.begin(), free_b_dims.end());
  Tensor C(out_shape);
  C.data = Cm.data;                                       // reshape back: again just reinterpretation
  return C;
}
