; ModuleID = 'LLVMDialectModule'
source_filename = "LLVMDialectModule"

%0 = type { i64, i64, ptr, ptr, ptr }

@add_tensors_kernel_bin_cst = internal constant [1248 x i8] c"//\0A// Generated by LLVM NVPTX Back-End\0A//\0A\0A.version 6.0\0A.target sm_70\0A.address_size 64\0A\0A\09// .globl\09add_tensors_kernel\0A\0A.visible .entry add_tensors_kernel(\0A\09.param .u64 add_tensors_kernel_param_0,\0A\09.param .u64 add_tensors_kernel_param_1,\0A\09.param .u64 add_tensors_kernel_param_2,\0A\09.param .u64 add_tensors_kernel_param_3,\0A\09.param .u64 add_tensors_kernel_param_4\0A)\0A{\0A\09.reg .b32 \09%r<3>;\0A\09.reg .b64 \09%rd<19>;\0A\09.reg .f64 \09%fd<4>;\0A\0A\09ld.param.u64 \09%rd1, [add_tensors_kernel_param_0];\0A\09ld.param.u64 \09%rd2, [add_tensors_kernel_param_4];\0A\09cvta.to.global.u64 \09%rd3, %rd2;\0A\09ld.param.u64 \09%rd4, [add_tensors_kernel_param_1];\0A\09ld.param.u64 \09%rd5, [add_tensors_kernel_param_3];\0A\09cvta.to.global.u64 \09%rd6, %rd5;\0A\09ld.param.u64 \09%rd7, [add_tensors_kernel_param_2];\0A\09cvta.to.global.u64 \09%rd8, %rd7;\0A\09mov.u32 \09%r1, %ctaid.x;\0A\09cvt.s64.s32 \09%rd9, %r1;\0A\09mov.u32 \09%r2, %tid.x;\0A\09cvt.s64.s32 \09%rd10, %r2;\0A\09mul.lo.s64 \09%rd11, %rd9, %rd1;\0A\09add.s64 \09%rd12, %rd11, %rd4;\0A\09shl.b64 \09%rd13, %rd12, 1;\0A\09add.s64 \09%rd14, %rd13, %rd10;\0A\09shl.b64 \09%rd15, %rd14, 3;\0A\09add.s64 \09%rd16, %rd8, %rd15;\0A\09ld.global.f64 \09%fd1, [%rd16];\0A\09add.s64 \09%rd17, %rd6, %rd15;\0A\09ld.global.f64 \09%fd2, [%rd17];\0A\09add.rn.f64 \09%fd3, %fd1, %fd2;\0A\09add.s64 \09%rd18, %rd3, %rd15;\0A\09st.global.f64 \09[%rd18], %fd3;\0A\09ret;\0A\0A}\0A\00", align 8
@add_tensors_kernel_add_tensors_kernel_kernel_name = private unnamed_addr constant [19 x i8] c"add_tensors_kernel\00", align 1

declare ptr @malloc(i64)

define { ptr, ptr, i64, [2 x i64], [2 x i64] } @add_tensors(ptr %0, ptr %1, i64 %2, i64 %3, i64 %4, i64 %5, i64 %6, ptr %7, ptr %8, i64 %9, i64 %10, i64 %11, i64 %12, i64 %13) {
  %15 = call ptr @mgpuStreamCreate()
  %16 = call ptr @mgpuMemAlloc(i64 ptrtoint (ptr getelementptr (double, ptr null, i32 4) to i64), ptr %15, i8 0)
  %17 = call ptr @mgpuMemAlloc(i64 ptrtoint (ptr getelementptr (double, ptr null, i32 4) to i64), ptr %15, i8 0)
  %18 = call ptr @mgpuMemAlloc(i64 ptrtoint (ptr getelementptr (double, ptr null, i32 4) to i64), ptr %15, i8 0)
  call void @mgpuMemcpy(ptr %16, ptr %1, i64 ptrtoint (ptr getelementptr (double, ptr null, i32 4) to i64), ptr %15)
  call void @mgpuMemcpy(ptr %17, ptr %8, i64 ptrtoint (ptr getelementptr (double, ptr null, i32 4) to i64), ptr %15)
  %19 = alloca %0, align 8
  %20 = alloca ptr, i64 5, align 8
  %21 = getelementptr inbounds %0, ptr %19, i32 0, i32 0
  store i64 1, ptr %21, align 4
  %22 = getelementptr ptr, ptr %20, i32 0
  store ptr %21, ptr %22, align 8
  %23 = getelementptr inbounds %0, ptr %19, i32 0, i32 1
  store i64 0, ptr %23, align 4
  %24 = getelementptr ptr, ptr %20, i32 1
  store ptr %23, ptr %24, align 8
  %25 = getelementptr inbounds %0, ptr %19, i32 0, i32 2
  store ptr %16, ptr %25, align 8
  %26 = getelementptr ptr, ptr %20, i32 2
  store ptr %25, ptr %26, align 8
  %27 = getelementptr inbounds %0, ptr %19, i32 0, i32 3
  store ptr %17, ptr %27, align 8
  %28 = getelementptr ptr, ptr %20, i32 3
  store ptr %27, ptr %28, align 8
  %29 = getelementptr inbounds %0, ptr %19, i32 0, i32 4
  store ptr %18, ptr %29, align 8
  %30 = getelementptr ptr, ptr %20, i32 4
  store ptr %29, ptr %30, align 8
  %31 = call ptr @mgpuModuleLoadJIT(ptr @add_tensors_kernel_bin_cst, i32 2)
  %32 = call ptr @mgpuModuleGetFunction(ptr %31, ptr @add_tensors_kernel_add_tensors_kernel_kernel_name)
  call void @mgpuLaunchKernel(ptr %32, i64 2, i64 1, i64 1, i64 2, i64 1, i64 1, i32 0, ptr %15, ptr %20, ptr null, i64 5)
  call void @mgpuModuleUnload(ptr %31)
  call void @mgpuStreamSynchronize(ptr %15)
  call void @mgpuStreamDestroy(ptr %15)
  %33 = call ptr @malloc(i64 ptrtoint (ptr getelementptr (double, ptr null, i32 4) to i64))
  %34 = insertvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } undef, ptr %33, 0
  %35 = insertvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } %34, ptr %33, 1
  %36 = insertvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } %35, i64 0, 2
  %37 = insertvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } %36, i64 2, 3, 0
  %38 = insertvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } %37, i64 2, 3, 1
  %39 = insertvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } %38, i64 2, 4, 0
  %40 = insertvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } %39, i64 1, 4, 1
  %41 = call ptr @mgpuStreamCreate()
  call void @mgpuMemcpy(ptr %33, ptr %18, i64 ptrtoint (ptr getelementptr (double, ptr null, i32 4) to i64), ptr %41)
  call void @mgpuMemFree(ptr %16, ptr %41)
  call void @mgpuMemFree(ptr %17, ptr %41)
  call void @mgpuMemFree(ptr %18, ptr %41)
  call void @mgpuStreamSynchronize(ptr %41)
  call void @mgpuStreamDestroy(ptr %41)
  ret { ptr, ptr, i64, [2 x i64], [2 x i64] } %40
}

declare ptr @mgpuStreamCreate()

declare ptr @mgpuMemAlloc(i64, ptr, i8)

declare void @mgpuMemcpy(ptr, ptr, i64, ptr)

declare void @mgpuStreamSynchronize(ptr)

declare void @mgpuStreamDestroy(ptr)

declare void @mgpuMemFree(ptr, ptr)

declare ptr @mgpuModuleLoadJIT(ptr, i32)

declare ptr @mgpuModuleGetFunction(ptr, ptr)

declare void @mgpuLaunchKernel(ptr, i64, i64, i64, i64, i64, i64, i32, ptr, ptr, ptr, i64)

declare void @mgpuModuleUnload(ptr)

!llvm.module.flags = !{!0}

!0 = !{i32 2, !"Debug Info Version", i32 3}
